name: Compatibility Testing

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'  # Run monthly
  workflow_dispatch:

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        numpy-version: ['1.20.0', '1.22.0', '1.24.0']
        matplotlib-version: ['3.4.0', '3.5.0', '3.6.0']
        networkx-version: ['2.6.0', '2.7.0', '2.8.0']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies with specific versions
      run: |
        python -m pip install --upgrade pip
        pip install numpy==${{ matrix.numpy-version }} matplotlib==${{ matrix.matplotlib-version }} networkx==${{ matrix.networkx-version }}
        pip install -e ".[test]"

    - name: Test with pytest
      run: |
        pytest tests/
      continue-on-error: true

    - name: Report compatibility status
      run: |
        echo "Tested with:"
        echo "  - NumPy: ${{ matrix.numpy-version }}"
        echo "  - Matplotlib: ${{ matrix.matplotlib-version }}"
        echo "  - NetworkX: ${{ matrix.networkx-version }}"