name: Documentation

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true
        commit_message: "Deploy documentation for ${{ github.sha }}"

    - name: Trigger ReadTheDocs build
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"token": "${{ secrets.READTHEDOCS_TOKEN }}"}' \
          https://readthedocs.org/api/v3/projects/memorial-tree/webhook/